language: python

python:
- "2.7"

before_install:
- sudo apt-get install -y closure-compiler nodejs npm
- sudo npm config set ca ""
- sudo npm config set strict-ssl false
- sudo npm install -g jshint

install:
- mkdir -p ./pages_out
- pip install -r requirements-testing.txt
- pip install -r requirements.txt

script:
- python ./prepare_package_contents.py
- ./opkg-utils/opkg-build -O -o 0 -g 0 -Z gzip pack/

after_success:
- qa.sh
- python ./harvest.py

after_failure:
- qa.sh
- python ./harvest.py

before_deploy:
#- find ./pages_out
#- git status
- ./opkg-utils/opkg-make-index ./pages_out/ | tee ./pages_out/Packages
- gzip ./pages_out/Packages

deploy:
  provider: pages
  local_dir: ./pages_out
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  target_branch: gh-pages
  on:
    branch: master
